### ISSUE TITLE
[Feature request] Add temperature sensor and display switch

### ISSUE THREAD

**Issue by dimmuboy** [veista/smartthings#3]
- Would you add temperature sensor same like humidity?

- Another idea is turn on and off display. I have it done via rest command now.

```
livingroom_ac_display_on:
  url: https://api.smartthings.com/v1/devices/[device-id]/commands
  method: POST
  headers:
    User-Agent: Home Assistant
    Content-Type: application/json
    Authorization: !secret smartthings_token
  payload: '{"commands":[{"component":"main","capability":"execute","command":"execute","arguments":["mode/vs/0",{"x.com.samsung.da.options":["Light_Off"]}]}]}'
  content_type: application/json

```
